---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.20.3

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[crowi::standalone]
    attributes:
